# Generated by Django 2.0.3 on 2018-03-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='Without title', max_length=50),
            preserve_default=False,
        ),
    ]
